;;; package --- Summary

;;; Commentary:
;; Programs expected to be available at command line:
;; * agda-mode

;;; Code:

;; Generated by `agda-mode setup`
(load-file (let ((coding-system-for-read 'utf-8))
                (shell-command-to-string "agda-mode locate")))

(provide 'init-agda)
;;; init-agda.el ends here
